### ISSUE TITLE
Send webSocket ready upon press of button (to cut discussion time short if all players press it) Priority: high. Time: 1h.

### ISSUE THREAD

**Issue by DaKnechtCoder** [sopra-fs24-group-42/client#20]

**Comment by kuppolina** [comment]
commit https://github.com/sopra-fs24-group-42/client/commit/957863a0c0f08acd9b8dc124bff91fa9a888293d and https://github.com/sopra-fs24-group-42/client/commit/8321bf751e1af634f6394a5e69e143c6861f203b closes this issue
