### ISSUE TITLE
Implement the relevant POST HTTP request (creation of player). Priority: high. Time: 0.25h

### ISSUE THREAD

**Issue by DaKnechtCoder** [sopra-fs24-group-42/client#8]

**Comment by cmodel1** [comment]
The commit 6a9a04c74d1cbd7a15e26ff7e3e9f4b939a6e8a1 closed this issue. Later it was reopened due to changes in the  necessary requests in createGame, which the commit 2fa741ed2f1c0b2e47510e7d5959974e75e9ee39 fixed.
